"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP_NAME='My Pairwise'
APP = ['app.py']
DATA_FILES = []
OPTIONS = {
    'packages':['allpairspy'],
    'iconfile':'AnyConv.com__sock_warm_icon.icns',
    'argv_emulation':True}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS

             },
    setup_requires=['py2app'],
)
